package br.com.esl.etl.v2.contratos;

/** Verificações fechadas que podem aparecer no resumo de evidência. */
public enum ContractEvidenceCheck {
    METADATA_OBSERVED,
    REQUIRED_FILTERS_DECLARED,
    EMPTY_WINDOW_CONFIRMED,
    ENVELOPE_VALID,
    TRANSPORT_CONFIRMED,
    JSON_CONTENT_TYPE_DECLARED,
    RETRY_AFTER_OBSERVED,
    LATE_CHANGE_SCOPE_OBSERVED,
    PAGE_SIZE_RESPECTED,
    POPULATED_WINDOW_HAS_AT_LEAST_THREE_PAGES,
    TERMINAL_EMPTY_PAGE_OBSERVED,
    PAGINATION_STABLE,
    ORDER_TOTAL_OR_CURSOR_CONFIRMED,
    COVERAGE_CONFIRMED,
    SOURCE_TIMEZONE_FORMALLY_CONFIRMED,
    IDENTITY_VOLUME_EQUAL,
    IDENTITY_CROSSWALK_ONE_TO_ONE,
    IDENTITY_SOURCE_IDS_EQUAL,
    FINANCIAL_EQUIVALENCE_CONFIRMED,
    FRETE_COLETA_RELATION_CONFIRMED,
    CTE_INVOICE_RELATION_CONFIRMED
}
