:On Error exit
SET NOCOUNT ON;
IF DB_NAME()<>N'master' OR CONVERT(NVARCHAR(128),SERVERPROPERTY('ServerName'))<>N'RTR-SVW-002'
 OR CONVERT(NVARCHAR(128),SERVERPROPERTY('MachineName'))<>N'RTR-SVW-002'
 OR SERVERPROPERTY('IsClustered')<>0 OR SERVERPROPERTY('IsHadrEnabled')<>0
 OR ORIGINAL_LOGIN()<>N'RTR-SVW-002\suporte'
 OR CONNECTIONPROPERTY('auth_scheme') NOT IN(N'NTLM',N'KERBEROS')
 OR (SELECT COUNT_BIG(*) FROM sys.databases WHERE name=N'ETL_SISTEMA_V2_SHADOW' AND state_desc=N'ONLINE' AND is_read_only=0)<>1
 THROW 52970,N'B60_EXACT_TARGET_AND_ADMIN_REQUIRED',1;
SELECT N'B60_EXACT_LOCAL_TARGET_CONFIRMED';