:On Error exit
SET NOCOUNT ON;SET XACT_ABORT ON;
IF DB_NAME()<>N'ETL_SISTEMA_V2_SHADOW' THROW 52970,N'B60_BARRIER_TARGET',1;
DECLARE @resource NVARCHAR(255)=N'V2_APPLY_'+CONVERT(NVARCHAR(64),HASHBYTES('SHA2_256',N'24:LOCAL_SHADOW|16:LOCAL_V2|16:LOCAL_V2|16:usuarios'),2),@result INT;
BEGIN TRANSACTION;
EXEC @result=sys.sp_getapplock @Resource=@resource,@LockMode=N'Exclusive',@LockOwner=N'Transaction',@LockTimeout=1000,@DbPrincipal=N'public';
IF @result<0 THROW 52970,N'B60_BARRIER_LOCK',1;
RAISERROR(N'B60_BARRIER_READY',0,1) WITH NOWAIT;
WAITFOR DELAY '00:00:08';
ROLLBACK TRANSACTION;
SELECT N'B60_BARRIER_RELEASED_ROLLBACK';