:On Error exit
SET NOCOUNT ON; SET XACT_ABORT ON;
IF DB_NAME()<>N'ETL_SISTEMA_V2_SHADOW' OR @@TRANCOUNT<>0 OR ORIGINAL_LOGIN()<>N'RTR-SVW-002\suporte'
 OR OBJECT_ID(N'ctl.source_protocol_binding') IS NOT NULL
 OR CONVERT(NVARCHAR(128),SERVERPROPERTY('ServerName'))<>N'RTR-SVW-002'
 THROW 52970,N'B60_EXACT_PRIOR_TARGET_REQUIRED',1;
:r "profile-before.sql"
:r "catalog.sql"
IF NOT EXISTS(SELECT 1 FROM ctl.source_catalog WHERE source_instance=N'LOCAL_V2' AND source_kind=N'DATA_EXPORT' AND active=1)
 THROW 52970,N'B60_ORIGINAL_LOGICAL_SOURCE_REQUIRED',1;
IF NOT EXISTS(SELECT 1 FROM ctl.runtime_authority_configuration WHERE authority_id='fd966e17-71c7-4071-9ccc-bedcaecffcd0')
 THROW 52970,N'B60_ORIGINAL_AUTHORITY_ID_REQUIRED',1;
SELECT N'B60_PREFLIGHT_ONLY_NO_MUTATION';
IF EXISTS(SELECT 1 FROM sys.dm_exec_sessions WHERE is_user_process=1 AND original_login_name IN(N'RTR-SVW-002\etl_v2_exec',N'RTR-SVW-002\etl_v2_view'))
 THROW 52970,N'B60_EXISTING_RESTRICTED_SESSION_STOP',1;
