package br.com.esl.etl.v2.modulos.fretes.aplicacao;

import br.com.esl.etl.v2.modulos.fretes.domain.FreightAnalyticAttributes;
import br.com.esl.etl.v2.plataforma.fonte.dataexport.AnalyticScalarParser;
import br.com.esl.etl.v2.plataforma.fonte.dataexport.ExpansionFieldParser;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.Set;

/**
 * Closed synthetic source channel; legacy GraphQL attributes do not become a Data Export contract.
 */
public final class FreightAnalyticAttributesMapper {
    private static final Set<String> FIELDS =
            Set.of(
                    "modal",
                    "tipo_frete",
                    "accounting_credit_id",
                    "accounting_credit_installment_id",
                    "valor_notas",
                    "peso_notas",
                    "id_corporacao",
                    "id_cidade_destino",
                    "data_previsao_entrega",
                    "service_date",
                    "pick_item_id",
                    "pagador_id",
                    "pagador_nome",
                    "remetente_id",
                    "remetente_nome",
                    "origem_cidade",
                    "origem_uf",
                    "destinatario_id",
                    "destinatario_nome",
                    "destino_cidade",
                    "destino_uf",
                    "filial_nome",
                    "filial_apelido",
                    "numero_nota_fiscal",
                    "tabela_preco_nome",
                    "classificacao_nome",
                    "centro_custo_nome",
                    "usuario_nome",
                    "invoices_total_volumes",
                    "taxed_weight",
                    "real_weight",
                    "total_cubic_volume",
                    "subtotal",
                    "chave_cte",
                    "numero_cte",
                    "serie_cte",
                    "cte_id",
                    "cte_emission_type",
                    "service_type",
                    "insurance_enabled",
                    "gris_subtotal",
                    "tde_subtotal",
                    "modal_cte",
                    "redispatch_subtotal",
                    "suframa_subtotal",
                    "payment_type",
                    "previous_document_type",
                    "products_value",
                    "trt_subtotal",
                    "nfse_series",
                    "nfse_number",
                    "insurance_id",
                    "other_fees",
                    "km",
                    "payment_accountable_type",
                    "insured_value",
                    "globalized",
                    "sec_cat_subtotal",
                    "globalized_type",
                    "price_table_accountable_type",
                    "insurance_accountable_type",
                    "fiscal_calculation_basis",
                    "fiscal_tax_rate",
                    "fiscal_pis_rate",
                    "fiscal_cofins_rate",
                    "fiscal_has_difal",
                    "fiscal_difal_origin",
                    "fiscal_difal_destination",
                    "fiscal_cst_type",
                    "fiscal_cfop_code",
                    "fiscal_tax_value",
                    "fiscal_pis_value",
                    "fiscal_cofins_value",
                    "cubages_cubed_weight",
                    "freight_weight_subtotal",
                    "ad_valorem_subtotal",
                    "toll_subtotal",
                    "itr_subtotal",
                    "pagador_documento",
                    "remetente_documento",
                    "destinatario_documento",
                    "filial_cnpj",
                    "nfse_integration_id",
                    "nfse_status",
                    "nfse_issued_at",
                    "nfse_cancelation_reason",
                    "nfse_pdf_service_url",
                    "nfse_corporation_id",
                    "nfse_service_description",
                    "nfse_xml_document");

    public FreightAnalyticAttributes map(final JsonNode envelope) {
        if (envelope == null
                || !envelope.isObject()
                || envelope.size() != 3
                || !"FIXTURE_SINTETICA_EXPLICITA".equals(envelope.path("provenance").asText())
                || !"synthetic-freight-attributes-v1".equals(envelope.path("version").asText())
                || !envelope.path("attributes").isObject()) {
            throw new IllegalArgumentException("ANA_FREIGHT_ATTRIBUTE_ENVELOPE");
        }
        final var row = envelope.path("attributes");
        row.fieldNames()
                .forEachRemaining(
                        name -> {
                            if (!FIELDS.contains(name)) {
                                throw new IllegalArgumentException("ANA_FREIGHT_ATTRIBUTE_UNKNOWN");
                            }
                        });
        return new FreightAnalyticAttributes(
                AnalyticScalarParser.text(row, "modal", 50),
                AnalyticScalarParser.text(row, "tipo_frete", 100),
                AnalyticScalarParser.longInteger(row, "accounting_credit_id"),
                AnalyticScalarParser.longInteger(row, "accounting_credit_installment_id"),
                ExpansionFieldParser.decimal(row, "valor_notas"),
                ExpansionFieldParser.decimal(row, "peso_notas"),
                AnalyticScalarParser.longInteger(row, "id_corporacao"),
                AnalyticScalarParser.longInteger(row, "id_cidade_destino"),
                ExpansionFieldParser.date(row, "data_previsao_entrega"),
                ExpansionFieldParser.date(row, "service_date"),
                AnalyticScalarParser.longInteger(row, "pick_item_id"),
                AnalyticScalarParser.longInteger(row, "pagador_id"),
                AnalyticScalarParser.text(row, "pagador_nome", 255),
                AnalyticScalarParser.longInteger(row, "remetente_id"),
                AnalyticScalarParser.text(row, "remetente_nome", 255),
                AnalyticScalarParser.text(row, "origem_cidade", 255),
                AnalyticScalarParser.text(row, "origem_uf", 10),
                AnalyticScalarParser.longInteger(row, "destinatario_id"),
                AnalyticScalarParser.text(row, "destinatario_nome", 255),
                AnalyticScalarParser.text(row, "destino_cidade", 255),
                AnalyticScalarParser.text(row, "destino_uf", 10),
                AnalyticScalarParser.text(row, "filial_nome", 255),
                AnalyticScalarParser.text(row, "filial_apelido", 255),
                AnalyticScalarParser.text(row, "numero_nota_fiscal", 1024),
                AnalyticScalarParser.text(row, "tabela_preco_nome", 255),
                AnalyticScalarParser.text(row, "classificacao_nome", 255),
                AnalyticScalarParser.text(row, "centro_custo_nome", 255),
                AnalyticScalarParser.text(row, "usuario_nome", 255),
                AnalyticScalarParser.integer(row, "invoices_total_volumes"),
                ExpansionFieldParser.decimal(row, "taxed_weight"),
                ExpansionFieldParser.decimal(row, "real_weight"),
                ExpansionFieldParser.decimal(row, "total_cubic_volume"),
                ExpansionFieldParser.decimal(row, "subtotal"),
                AnalyticScalarParser.text(row, "chave_cte", 100),
                AnalyticScalarParser.integer(row, "numero_cte"),
                AnalyticScalarParser.integer(row, "serie_cte"),
                AnalyticScalarParser.longInteger(row, "cte_id"),
                AnalyticScalarParser.text(row, "cte_emission_type", 50),
                AnalyticScalarParser.integer(row, "service_type"),
                ExpansionFieldParser.bool(row, "insurance_enabled"),
                ExpansionFieldParser.decimal(row, "gris_subtotal"),
                ExpansionFieldParser.decimal(row, "tde_subtotal"),
                AnalyticScalarParser.text(row, "modal_cte", 50),
                ExpansionFieldParser.decimal(row, "redispatch_subtotal"),
                ExpansionFieldParser.decimal(row, "suframa_subtotal"),
                AnalyticScalarParser.text(row, "payment_type", 50),
                AnalyticScalarParser.text(row, "previous_document_type", 50),
                ExpansionFieldParser.decimal(row, "products_value"),
                ExpansionFieldParser.decimal(row, "trt_subtotal"),
                AnalyticScalarParser.text(row, "nfse_series", 50),
                AnalyticScalarParser.integer(row, "nfse_number"),
                AnalyticScalarParser.longInteger(row, "insurance_id"),
                ExpansionFieldParser.decimal(row, "other_fees"),
                ExpansionFieldParser.decimal(row, "km"),
                AnalyticScalarParser.integer(row, "payment_accountable_type"),
                ExpansionFieldParser.decimal(row, "insured_value"),
                ExpansionFieldParser.bool(row, "globalized"),
                ExpansionFieldParser.decimal(row, "sec_cat_subtotal"),
                AnalyticScalarParser.text(row, "globalized_type", 50),
                AnalyticScalarParser.integer(row, "price_table_accountable_type"),
                AnalyticScalarParser.integer(row, "insurance_accountable_type"),
                ExpansionFieldParser.decimal(row, "fiscal_calculation_basis"),
                ExpansionFieldParser.decimal(row, "fiscal_tax_rate"),
                ExpansionFieldParser.decimal(row, "fiscal_pis_rate"),
                ExpansionFieldParser.decimal(row, "fiscal_cofins_rate"),
                ExpansionFieldParser.bool(row, "fiscal_has_difal"),
                ExpansionFieldParser.decimal(row, "fiscal_difal_origin"),
                ExpansionFieldParser.decimal(row, "fiscal_difal_destination"),
                AnalyticScalarParser.text(row, "fiscal_cst_type", 10),
                AnalyticScalarParser.text(row, "fiscal_cfop_code", 10),
                ExpansionFieldParser.decimal(row, "fiscal_tax_value"),
                ExpansionFieldParser.decimal(row, "fiscal_pis_value"),
                ExpansionFieldParser.decimal(row, "fiscal_cofins_value"),
                ExpansionFieldParser.decimal(row, "cubages_cubed_weight"),
                ExpansionFieldParser.decimal(row, "freight_weight_subtotal"),
                ExpansionFieldParser.decimal(row, "ad_valorem_subtotal"),
                ExpansionFieldParser.decimal(row, "toll_subtotal"),
                ExpansionFieldParser.decimal(row, "itr_subtotal"),
                AnalyticScalarParser.text(row, "pagador_documento", 50),
                AnalyticScalarParser.text(row, "remetente_documento", 50),
                AnalyticScalarParser.text(row, "destinatario_documento", 50),
                AnalyticScalarParser.text(row, "filial_cnpj", 50),
                AnalyticScalarParser.text(row, "nfse_integration_id", 50),
                AnalyticScalarParser.text(row, "nfse_status", 50),
                ExpansionFieldParser.date(row, "nfse_issued_at"),
                AnalyticScalarParser.text(row, "nfse_cancelation_reason", 255),
                AnalyticScalarParser.text(row, "nfse_pdf_service_url", 1000),
                AnalyticScalarParser.longInteger(row, "nfse_corporation_id"),
                AnalyticScalarParser.text(row, "nfse_service_description", 500),
                AnalyticScalarParser.text(row, "nfse_xml_document", 1024));
    }
}
