package br.com.esl.etl.v2.plataforma.resiliencia;

/** Taxonomia fechada; nenhum texto de exceção participa da decisão. */
public enum FailureKind {
    CONFIGURATION,
    IDENTITY,
    AUTHORIZATION,
    SCHEMA_CONTRACT,
    CONTRACT_DRIFT,
    SQL_FAILURE,
    LOCK_UNAVAILABLE,
    CRITICAL_DATA_QUALITY,
    RATE_LIMIT,
    REQUEST_TIMEOUT,
    STEP_TIMEOUT,
    CYCLE_TIMEOUT,
    HTTP_5XX,
    SOURCE_UNAVAILABLE,
    CIRCUIT_OPEN,
    SOURCE_BUDGET_EXHAUSTED,
    WORKLOAD_BUDGET_EXHAUSTED,
    WINDOW_TOO_LARGE_HTTP_422,
    UNCLASSIFIED_HTTP_422,
    PERMANENT_SOURCE_REJECTION,
    REQUIRED_DEPENDENCY_FAILED,
    OPTIONAL_DEPENDENCY_FAILED,
    OPTIONAL_SOURCE_UNAVAILABLE,
    SOURCE_DISABLED,
    NON_CRITICAL_OBSERVABILITY,
    CANCELLATION
}
