#Requires -Version 7.0

[CmdletBinding()]
param(
    [switch]$VerifyGenerated
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repositoryRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
$matrixPath = Join-Path $repositoryRoot 'docs\catalogos\sweep-v2-013\matriz-aplicabilidade-v01.csv'
$utf8NoBom = [Text.UTF8Encoding]::new($false, $true)

function New-Row {
    param(
        [Parameter(Mandatory)][string]$RowId,
        [Parameter(Mandatory)][string]$Family,
        [Parameter(Mandatory)][string]$Responsibility,
        [Parameter(Mandatory)][string]$RowKind,
        [AllowEmptyString()][string]$ParentRowId,
        [Parameter(Mandatory)][string]$Applicability,
        [Parameter(Mandatory)][string]$OwnerStatus,
        [Parameter(Mandatory)][string]$HierarchyPolicy,
        [Parameter(Mandatory)][string]$PresenceKey,
        [Parameter(Mandatory)][string]$ReasonCode,
        [Parameter(Mandatory)][string]$EvidenceAnchor
    )
    $presenceKeyPath = switch ($RowId) {
        'SWP-COLETAS-ROOT' { '/id' }
        'SWP-FRETES-ROOT' { '/id' }
        'SWP-MANIFESTOS-ROOT' { '/sequence_code' }
        'SWP-MANIFESTOS-PICK' { '/mft_pfs_pck_sequence_code' }
        'SWP-MANIFESTOS-MDFE' { '/mft_mfs_key' }
        'SWP-COTACOES-ROOT' { '/sequence_code' }
        'SWP-LOCALIZACAO-ROOT' { '/corporation_sequence_number' }
        'SWP-FATURAS-ROOT-CAND' { '/id' }
        'SWP-CAP-PARCELA-CAND' { '/ant_ils_sequence_code' }
        'SWP-FATURAS-TITULO-CAND' { '/fit_ant_document' }
        'SWP-FATURAS-NFSE-CAND' { '/fit_nse_number|/nfse_number' }
        'SWP-FATURAS-CTE-CAND' { '/fit_fhe_cte_number|/fit_fhe_cte_key' }
        'SWP-FATURAS-BILLING-CAND' { 'UNOBSERVED_LEGACY_HEURISTIC:billingId' }
        'SWP-FATURAS-INVOICE-CAND' { '/invoices_mapping/*' }
        'SWP-FATURAS-ORDER-CAND' { '/fit_fte_invoices_order_number/*' }
        'SWP-INVENTARIO-ROOT-CAND' { '/sequence_code' }
        'SWP-INVENTARIO-FREIGHT-CAND' { '/cnr_c_s_fit_corporation_sequence_number' }
        'SWP-INVENTARIO-INVOICE-CAND' { '/cnr_c_s_fit_invoices_mapping/*' }
        'SWP-SINISTROS-ROOT-CAND' { '/sequence_code' }
        'SWP-SINISTROS-MINUTA-CAND' { '/icm_fis_fit_corporation_sequence_number' }
        'SWP-SINISTROS-INVOICE-CAND' { '/icm_fis_ioe_number' }
        'SWP-USUARIOS-CURRENT' { '/node/id' }
        'SWP-RASTER-VIAGENS' { 'LEGACY_COLUMN_CANDIDATE:cod_solicitacao' }
        'SWP-RASTER-PARADAS' { 'LEGACY_COMPOSITE_CANDIDATE:cod_solicitacao+ordem' }
        default { 'NONE_UNRESOLVED_OR_PARENT_OWNED' }
    }
    $presenceKeyValue = switch ($RowKind) {
        'ROOT' { 'SCOPED_TYPED_SOURCE_KEY' }
        'SOURCE_LINE' { 'SCOPED_SOURCE_LINE_KEY_NOT_LOGICAL_ROOT' }
        'CHILD' { 'SCOPED_TYPED_CHILD_KEY_OWNED_BY_PARENT' }
        'ONE_TO_ONE_COMPONENT' { 'PARENT_CANONICAL_ID_ONLY' }
        'HISTORY' { 'PARENT_CANONICAL_ID_PLUS_VERSION' }
        default { 'NO_ACCEPTED_PRESENCE_KEY' }
    }
    $confirmationPolicy = if ($Applicability -in @('BLOCKED', 'DISABLED')) {
        'V2_012B_ACCEPTED+NOMINAL_SNAPSHOT_COMPLETENESS_PROOF+SOURCE_COMPLETENESS_PROVEN_COMPLETE+OWNER_NOMINAL+TWO_COMPLETE_TRAVERSALS+TWO_INDEPENDENT_ABSENCES'
    } else {
        'NOT_APPLICABLE_OR_IDENTITY_CARDINALITY_PENDING'
    }
    if ($RowKind -eq 'CHILD') {
        $confirmationPolicy += '+PARENT_ROOT_ASSESSMENT_BOUND'
    }
    return [pscustomobject][ordered]@{
        row_id = $RowId
        family = $Family
        responsibility = $Responsibility
        row_kind = $RowKind
        parent_row_id = $ParentRowId
        applicability = $Applicability
        completeness_status = 'BLOCKED_NO_COMPLETENESS_PROOF'
        owner_status = $OwnerStatus
        hierarchy_policy = $HierarchyPolicy
        presence_key_path = $presenceKeyPath
        presence_key_value = $presenceKeyValue
        presence_key_status = $PresenceKey
        confirmation_policy = $confirmationPolicy
        guardrail_policy = 'PREVIEW_ONLY+NO_APPLY+NO_DELETE+NO_DEACTIVATE+NO_PRUNE+NO_PERSIST+NO_ENTITY_ENABLEMENT+BLOCK_TIMEOUT+BLOCK_MISSING_PAGE+BLOCK_CAP+BLOCK_ANOMALOUS_EMPTY+BLOCK_INVALIDS+BLOCK_QUARANTINE+BLOCK_STRONG_VOLUME_DROP+BLOCK_HISTORY_GAP'
        reason_code = $ReasonCode
        evidence_anchor = $EvidenceAnchor
    }
}

$rows = @(
    New-Row 'SWP-COLETAS-ROOT' 'COLETAS' 'coletas_root' 'ROOT' '' 'BLOCKED' 'NOMINAL_OWNER_PENDING' 'ROOT_ONLY' 'ROOT_SOURCE_KEY_ACCEPTED_COMPLETENESS_PENDING' 'ENTITY_SWEEP_GATE_OPEN' 'V2-010;Q-*-04'
    New-Row 'SWP-COLETAS-FRETE-CAND' 'COLETAS' 'coleta_frete_relation_candidate' 'UNRESOLVED_CANDIDATE' 'SWP-COLETAS-ROOT' 'NOT_APPLICABLE' 'NOT_APPLICABLE' 'RELATION_DEFERRED' 'UNRESOLVED_CANDIDATE_NO_PRESENCE_KEY' 'CROSSWALK_OWNER_V2_046B' 'COL-07;V2-046b'
    New-Row 'SWP-FRETES-ROOT' 'FRETES' 'fretes_root' 'ROOT' '' 'DISABLED' 'NOMINAL_OWNER_PENDING' 'ROOT_ONLY' 'ROOT_SOURCE_KEY_ACCEPTED_COMPLETENESS_PENDING' 'ENTITY_SWEEP_DISABLED_PENDING_ACCEPTED_COMPLETENESS_AND_OWNER' 'V2-011;Q-*-04'
    New-Row 'SWP-FRETES-PERFORMANCE' 'FRETES' 'frete_performance' 'ONE_TO_ONE_COMPONENT' 'SWP-FRETES-ROOT' 'NOT_APPLICABLE' 'INHERITS_PARENT_OWNER' 'PARENT_OWNED_ATOMIC' 'PARENT_OWNED_NOT_INDEPENDENT' 'NO_INDEPENDENT_ACTIVE_LIFECYCLE' 'V013;FRE-03'
    New-Row 'SWP-FRETES-GRAPHQL' 'FRETES' 'fretes_graphql_sidecar' 'OBSERVATION_CHANNEL' '' 'NOT_APPLICABLE' 'NOT_APPLICABLE' 'NOT_A_CHILD' 'OBSERVATION_ONLY_NO_PRESENCE_AUTHORITY' 'SIDECAR_NOT_ROOT_OR_CHILD' 'Q-FND-02;FRE-04'
    New-Row 'SWP-FRETES-COLETA-CAND' 'FRETES' 'frete_coleta_relation_candidate' 'UNRESOLVED_CANDIDATE' 'SWP-FRETES-ROOT' 'NOT_APPLICABLE' 'NOT_APPLICABLE' 'RELATION_DEFERRED' 'UNRESOLVED_CANDIDATE_NO_PRESENCE_KEY' 'CROSSWALK_OWNER_V2_046B' 'V013;FRE-04;V2-046b'
    New-Row 'SWP-MANIFESTOS-ROOT' 'MANIFESTOS' 'manifestos_root' 'ROOT' '' 'BLOCKED' 'NOMINAL_OWNER_PENDING' 'ROOT_WITH_CHILDREN' 'ROOT_SOURCE_KEY_ACCEPTED_COMPLETENESS_PENDING' 'ENTITY_SWEEP_GATE_OPEN' 'V2-026;Q-*-04'
    New-Row 'SWP-MANIFESTOS-PICK' 'MANIFESTOS' 'manifesto_pick' 'CHILD' 'SWP-MANIFESTOS-ROOT' 'BLOCKED' 'INHERITS_PARENT_OWNER' 'PARENT_BINDING_AND_ATOMIC_PROPAGATION_PENDING_ENTITY_PLANNER' 'CHILD_IDENTITY_OWNED_BY_PARENT' 'CHILD_COMPLETENESS_NOT_PROVEN' 'V012;MAN-01;MAN-02'
    New-Row 'SWP-MANIFESTOS-MDFE' 'MANIFESTOS' 'manifesto_mdfe' 'CHILD' 'SWP-MANIFESTOS-ROOT' 'BLOCKED' 'INHERITS_PARENT_OWNER' 'PARENT_BINDING_AND_ATOMIC_PROPAGATION_PENDING_ENTITY_PLANNER' 'CHILD_IDENTITY_OWNED_BY_PARENT' 'CHILD_COMPLETENESS_NOT_PROVEN' 'V012;MAN-01;MAN-02'
    New-Row 'SWP-MANIFESTOS-COLETA-CAND' 'MANIFESTOS' 'manifesto_coleta_relation_candidate' 'UNRESOLVED_CANDIDATE' 'SWP-MANIFESTOS-ROOT' 'NOT_APPLICABLE' 'NOT_APPLICABLE' 'RELATION_DEFERRED' 'UNRESOLVED_CANDIDATE_NO_PRESENCE_KEY' 'CROSSWALK_OWNER_V2_046A' 'MAN-03;V2-046a'
    New-Row 'SWP-COTACOES-ROOT' 'COTACOES' 'cotacoes_root' 'ROOT' '' 'BLOCKED' 'NOMINAL_OWNER_PENDING' 'ROOT_ONLY' 'ROOT_SOURCE_KEY_ACCEPTED_COMPLETENESS_PENDING' 'ENTITY_SWEEP_GATE_OPEN' 'V2-027;Q-*-04'
    New-Row 'SWP-COTACOES-TARIFA-REF' 'COTACOES' 'tarifa_rota_uf_reference' 'REFERENCE' '' 'NOT_APPLICABLE' 'REFERENCE_OWNER_SEPARATE' 'NOT_ENTITY_HIERARCHY' 'REFERENCE_RELEASE_NOT_PRESENCE' 'REFERENCE_NOT_SWEEP_RESPONSIBILITY' 'COT-02;V2-035a'
    New-Row 'SWP-LOCALIZACAO-ROOT' 'LOCALIZACAO_CARGAS' 'localizacao_cargas_root' 'ROOT' '' 'DISABLED' 'NOMINAL_OWNER_PENDING' 'ROOT_ONLY' 'ROOT_SOURCE_KEY_ACCEPTED_COMPLETENESS_PENDING' 'ENTITY_SWEEP_DISABLED_PENDING_ACCEPTED_COMPLETENESS_AND_OWNER' 'V2-028;Q-*-04'
    New-Row 'SWP-LOCALIZACAO-FRETE-CAND' 'LOCALIZACAO_CARGAS' 'localizacao_frete_relation_candidate' 'UNRESOLVED_CANDIDATE' 'SWP-LOCALIZACAO-ROOT' 'NOT_APPLICABLE' 'NOT_APPLICABLE' 'RELATION_DEFERRED' 'UNRESOLVED_CANDIDATE_NO_PRESENCE_KEY' 'FREIGHT_FALLBACK_DEFERRED' 'LOC-03;V2-046b'
    New-Row 'SWP-CAP-ROOT-CAND' 'CONTAS_A_PAGAR' 'contas_a_pagar_root_candidate' 'UNRESOLVED_CANDIDATE' '' 'BLOCKED' 'NOMINAL_OWNER_PENDING' 'ROOT_UNRESOLVED' 'UNRESOLVED_CANDIDATE_NO_PRESENCE_KEY' 'VERTICAL_AND_IDENTITY_PENDING' 'V2-029;CAP-01'
    New-Row 'SWP-CAP-PARCELA-CAND' 'CONTAS_A_PAGAR' 'parcela_ant_ils_candidate' 'UNRESOLVED_CANDIDATE' 'SWP-CAP-ROOT-CAND' 'BLOCKED' 'NOMINAL_OWNER_PENDING' 'CARDINALITY_UNRESOLVED' 'CANDIDATE_PATH_PRESERVED_NOT_ACCEPTED_AS_PRESENCE_KEY' 'PARCEL_CARDINALITY_UNVERIFIED' 'identidade-contas-a-pagar;CAP-01;CAP-02;CAP-04'
    New-Row 'SWP-FATURAS-ROOT-CAND' 'FATURAS_POR_CLIENTE' 'fatura_por_cliente_source_line' 'SOURCE_LINE' '' 'NOT_APPLICABLE' 'NOMINAL_OWNER_PENDING' 'LOGICAL_ROOT_UNRESOLVED' 'SOURCE_LINE_KEY_ACCEPTED_NOT_LOGICAL_ROOT' 'SOURCE_LINE_IS_NOT_SWEEP_ROOT' 'V2-030;FAT-01'
    New-Row 'SWP-FATURAS-TITULO-CAND' 'FATURAS_POR_CLIENTE' 'logical_title_identity_candidate' 'UNRESOLVED_CANDIDATE' 'SWP-FATURAS-ROOT-CAND' 'BLOCKED' 'NOMINAL_OWNER_PENDING' 'IDENTITY_MAPPING_UNRESOLVED' 'CANDIDATE_PATH_PRESERVED_NOT_ACCEPTED_AS_PRESENCE_KEY' 'TITLE_MAPPING_NOT_MODELED' 'identidade-faturas-por-cliente;FAT-01'
    New-Row 'SWP-FATURAS-NFSE-CAND' 'FATURAS_POR_CLIENTE' 'nfse_mapping_candidate' 'UNRESOLVED_CANDIDATE' 'SWP-FATURAS-ROOT-CAND' 'BLOCKED' 'NOMINAL_OWNER_PENDING' 'CARDINALITY_UNRESOLVED' 'CANDIDATE_PATH_PRESERVED_NOT_ACCEPTED_AS_PRESENCE_KEY' 'NFSE_MAPPING_NOT_MODELED' 'identidade-faturas-por-cliente;FAT-01'
    New-Row 'SWP-FATURAS-CTE-CAND' 'FATURAS_POR_CLIENTE' 'cte_mapping_candidate' 'UNRESOLVED_CANDIDATE' 'SWP-FATURAS-ROOT-CAND' 'BLOCKED' 'NOMINAL_OWNER_PENDING' 'CARDINALITY_UNRESOLVED' 'CANDIDATE_PATH_PRESERVED_NOT_ACCEPTED_AS_PRESENCE_KEY' 'CTE_MAPPING_NOT_MODELED' 'identidade-faturas-por-cliente;FAT-01'
    New-Row 'SWP-FATURAS-BILLING-CAND' 'FATURAS_POR_CLIENTE' 'billing_id_legacy_heuristic_candidate' 'UNRESOLVED_CANDIDATE' 'SWP-FATURAS-ROOT-CAND' 'BLOCKED' 'NOMINAL_OWNER_PENDING' 'HEURISTIC_IDENTITY_FORBIDDEN' 'UNOBSERVED_LEGACY_HEURISTIC_NOT_ACCEPTED' 'BILLING_ID_HEURISTIC_NOT_A_PRESENCE_KEY' 'identidade-faturas-por-cliente;FAT-01'
    New-Row 'SWP-FATURAS-INVOICE-CAND' 'FATURAS_POR_CLIENTE' 'invoice_mapping_candidate' 'UNRESOLVED_CANDIDATE' 'SWP-FATURAS-ROOT-CAND' 'BLOCKED' 'NOMINAL_OWNER_PENDING' 'CARDINALITY_UNRESOLVED' 'CANDIDATE_PATH_PRESERVED_NOT_ACCEPTED_AS_PRESENCE_KEY' 'ARRAY_CHILD_NOT_MODELED' 'identidade-faturas-por-cliente;FAT-01'
    New-Row 'SWP-FATURAS-ORDER-CAND' 'FATURAS_POR_CLIENTE' 'order_number_mapping_candidate' 'UNRESOLVED_CANDIDATE' 'SWP-FATURAS-ROOT-CAND' 'BLOCKED' 'NOMINAL_OWNER_PENDING' 'CARDINALITY_UNRESOLVED' 'CANDIDATE_PATH_PRESERVED_NOT_ACCEPTED_AS_PRESENCE_KEY' 'ARRAY_CHILD_NOT_MODELED' 'identidade-faturas-por-cliente;FAT-01'
    New-Row 'SWP-INVENTARIO-ROOT-CAND' 'INVENTARIO' 'inventario_root_candidate' 'UNRESOLVED_CANDIDATE' '' 'BLOCKED' 'NOMINAL_OWNER_PENDING' 'ROOT_UNRESOLVED' 'CANDIDATE_PATH_PRESERVED_NOT_ACCEPTED_AS_PRESENCE_KEY' 'VERTICAL_AND_IDENTITY_PENDING' 'V2-031;INV-01'
    New-Row 'SWP-INVENTARIO-FREIGHT-CAND' 'INVENTARIO' 'freight_minuta_mapping_candidate' 'UNRESOLVED_CANDIDATE' 'SWP-INVENTARIO-ROOT-CAND' 'BLOCKED' 'NOMINAL_OWNER_PENDING' 'CARDINALITY_UNRESOLVED' 'CANDIDATE_PATH_PRESERVED_NOT_ACCEPTED_AS_PRESENCE_KEY' 'RELATION_NOT_MODELED' 'identidade-inventario;INV-03;INV-04'
    New-Row 'SWP-INVENTARIO-INVOICE-CAND' 'INVENTARIO' 'invoice_mapping_candidate' 'UNRESOLVED_CANDIDATE' 'SWP-INVENTARIO-ROOT-CAND' 'BLOCKED' 'NOMINAL_OWNER_PENDING' 'CARDINALITY_UNRESOLVED' 'CANDIDATE_PATH_PRESERVED_NOT_ACCEPTED_AS_PRESENCE_KEY' 'ARRAY_CHILD_NOT_MODELED' 'identidade-inventario;INV-01;INV-02'
    New-Row 'SWP-SINISTROS-ROOT-CAND' 'SINISTROS' 'sinistros_root_candidate' 'UNRESOLVED_CANDIDATE' '' 'BLOCKED' 'NOMINAL_OWNER_PENDING' 'ROOT_UNRESOLVED' 'CANDIDATE_PATH_PRESERVED_NOT_ACCEPTED_AS_PRESENCE_KEY' 'VERTICAL_AND_IDENTITY_PENDING' 'V2-032;SIN-01'
    New-Row 'SWP-SINISTROS-MINUTA-CAND' 'SINISTROS' 'minuta_scalar_candidate' 'UNRESOLVED_CANDIDATE' 'SWP-SINISTROS-ROOT-CAND' 'BLOCKED' 'NOMINAL_OWNER_PENDING' 'NOT_A_CONFIRMED_CHILD' 'CANDIDATE_PATH_PRESERVED_NOT_ACCEPTED_AS_PRESENCE_KEY' 'CHILDREN_EXPLICITLY_EMPTY' 'identidade-sinistros;SIN-01'
    New-Row 'SWP-SINISTROS-INVOICE-CAND' 'SINISTROS' 'invoice_occurrence_scalar_candidate' 'UNRESOLVED_CANDIDATE' 'SWP-SINISTROS-ROOT-CAND' 'BLOCKED' 'NOMINAL_OWNER_PENDING' 'NOT_A_CONFIRMED_CHILD' 'CANDIDATE_PATH_PRESERVED_NOT_ACCEPTED_AS_PRESENCE_KEY' 'CHILDREN_EXPLICITLY_EMPTY' 'identidade-sinistros;SIN-01'
    New-Row 'SWP-USUARIOS-CURRENT' 'USUARIOS' 'usuarios_current_root' 'ROOT' '' 'DISABLED' 'NOMINAL_OWNER_PENDING' 'CURRENT_ROOT_ONLY' 'ROOT_SOURCE_KEY_ACCEPTED_COMPLETENESS_PENDING' 'ENTITY_SWEEP_DISABLED_BY_ADR0019_PENDING_ACCEPTED_COMPLETENESS_AND_OWNER' 'V2-033;Q-*-04;ADR-0019'
    New-Row 'SWP-USUARIOS-HISTORY' 'USUARIOS' 'usuario_history' 'HISTORY' 'SWP-USUARIOS-CURRENT' 'NOT_APPLICABLE' 'INHERITS_PARENT_OWNER' 'APPEND_ONLY_HISTORY' 'PARENT_OWNED_NOT_INDEPENDENT' 'HISTORY_NEVER_SWEPT' 'V007;ADR-0019'
    New-Row 'SWP-RASTER-VIAGENS' 'RASTER' 'raster_viagens_conditional' 'CONDITIONAL_COMPONENT' '' 'DISABLED' 'NOMINAL_OWNER_PENDING' 'CONDITIONAL_ROOT' 'CONDITIONAL_KEY_CANDIDATE_NOT_SWEEP_PROOF' 'RASTER_DECISION_PENDING' 'V2-034a;V2-034b;RAS-01;RAS-06'
    New-Row 'SWP-RASTER-PARADAS' 'RASTER' 'raster_paradas_conditional' 'CONDITIONAL_COMPONENT' 'SWP-RASTER-VIAGENS' 'DISABLED' 'NOMINAL_OWNER_PENDING' 'CONDITIONAL_CHILD_ATOMIC' 'CONDITIONAL_KEY_CANDIDATE_NOT_SWEEP_PROOF' 'RASTER_DECISION_PENDING' 'V2-034a;V2-034b;RAS-01;RAS-06'
)

$csv = (($rows | ConvertTo-Csv -NoTypeInformation -UseQuotes AsNeeded) -join "`n") + "`n"

if ($VerifyGenerated) {
    if (-not (Test-Path -LiteralPath $matrixPath -PathType Leaf)) {
        throw 'V2_013_SWEEP_MATRIX_MISSING'
    }
    $actual = $utf8NoBom.GetString([IO.File]::ReadAllBytes($matrixPath))
    if ($actual -cne $csv) { throw 'V2_013_SWEEP_MATRIX_DRIFT' }
    Write-Output "V2_013_SWEEP_CATALOG status=PASS mode=VERIFY rows=$($rows.Count) families=11"
    exit 0
}

$directory = Split-Path -Parent $matrixPath
[IO.Directory]::CreateDirectory($directory) | Out-Null
[IO.File]::WriteAllText($matrixPath, $csv, $utf8NoBom)
Write-Output "V2_013_SWEEP_CATALOG status=PASS mode=BUILD rows=$($rows.Count) families=11"
