@{
    'COL-01' = @('id=SRC-A e sequence_code=SEQ-A criam um canonical_id e alias distintos', 'id ausente ou troca de id por sequence_code vai para quarentena')
    'COL-02' = @('status_updated_at válido vence finish_date e o bruto é preservado', 'status_updated_at inválido não vira data; bruto fica preservado e o fallback é marcado')
    'COL-03' = @('done retroativo supera pending e permanece terminal', 'registro done persistido não regride quando chega pending mais novo')
    'COL-04' = @('done publica código done, label Coletada e terminal=true', 'finished não pode ser rotulado Coletada nem reescrever o código bruto')
    'COL-05' = @('duas ausências independentes confirmam soft delete; reaparecimento limpa todo estado de ausência', 'uma única travessia incremental não confirma ausência nem hard-delete')
    'COL-06' = @('snapshot completo com todas as páginas permite avaliar presença', 'página vazia anômala, chave nula ou cap atingido não altera ativos')
    'COL-07' = @('pick e manifesto entram com componentes, presença e proveniência até o crosswalk provar 1:N', 'nome parecido ou join que multiplica a coleta não cria relação canônica')
    'COL-08' = @('CEP válido encontra regra vigente antes do fallback cidade/UF', 'CEP inválido não pode sobrepor uma regra cidade/UF válida')
    'COL-09' = @('partição request_date publicada avança checkpoint; overlap captura atualização tardia', 'maior updated_at observado não salta partição ausente nem vira watermark')
    'COL-10' = @('limite candidato só é ativado após medição, owner e teste de reset/bloqueio', 'copiar 90 dias, 500 ou 35% como default produtivo é rejeitado')
    'COL-11' = @('finished com motivo vazio publica Finalizada, Coleta Realizada e tentativas=1', 'pending não é terminal, não recebe Coleta Realizada e mantém tentativas=0')

    'FRE-01' = @('id=FRE-A resolve canonical_id e corporation_sequence_number fica como alias', 'corporation_sequence_number sozinho não é promovido a source key')
    'FRE-02' = @('cte_created_at presente vence cte_issued_at e o desempate total escolhe uma linha', 'updated_at ou chegada posterior não supera a precedência nem faz terminal regredir')
    'FRE-03' = @('resposta sem CT-e mantém o CT-e conhecido e registra campo ausente', 'campo omitido não sobrescreve CT-e, finalização ou performance com nulo')
    'FRE-04' = @('pick_item_id é stageado e relacionado set-based após prova de cardinalidade', 'fit_p_m_pck_sequence_code semelhante não é tratado como o mesmo identificador')
    'FRE-05' = @('snapshot completo autorizado com duas ausências e guardrails pode confirmar prune', 'incremental, zero anômalo ou queda acima do limite não executa prune')
    'FRE-06' = @('CT-e, conta, receita e filial com paridade e owner podem alimentar o corte', 'divergência financeira ou campo sem owner mantém publicação bloqueada')
    'FRE-07' = @('13/04/2026 e 04/13/2026 seguem formatos inequívocos contratados', '02/04/2026 sem formato provado vai à quarentena, não usa heurística')

    'MAN-01' = @('sequence_code cria uma raiz escopada; mft_pfs_pck_sequence_code e mft_mfs_key criam filhos naturais separados, enquanto mdfe_status permanece escalar da raiz', 'hash, ordem, número ou status MDF-e isolado e coocorrência não criam identidade, filho ou relação')
    'MAN-02' = @('a coorte do primeiro instante válido finished/closed/departured/created reduz raiz, pick e MDF-e separadamente por presença tri-state', 'empate divergente, MAX genérico, chegada posterior ou mdfe_status sem chave não decide nem cria filho')
    'MAN-03' = @('mft_pfs_pck_sequence_code é preservado como candidato com presença/proveniência para V2-046a', 'órfão não vira nulo, FK inválida nem join heurístico para Coleta/Frete')
    'MAN-04' = @('departured_at VALUE válido define competência; ABSENT/NULL usa created_at com proveniência', 'data inválida ou de extração não aciona fallback nem substitui competência')
    'MAN-05' = @('manifesto sem placa sentinela soma cada frete/coleta uma vez e soma capacidades', 'placa ACM0000 ou relação duplicada não entra nem duplica receita')
    'MAN-06' = @('classificação resolve por referência vigente e versionada com origem auditada', 'CNPJ ou nome hardcoded no código não decide frota/classificação')
    'MAN-07' = @('NULL e um único VALUE complementam a métrica na coorte, preservando zero e proveniência', 'zero e não zero ou quaisquer valores distintos não são somados nem resolvidos por MAX')

    'COT-01' = @('sequence_code identifica a cotação e nfse_issued_at vence cte_issued_at/requested_at', 'dedupe apenas por requested_at ou chegada posterior não pode regredir o registro')
    'COT-02' = @('UF origem/destino encontra tarifa vigente única na referência versionada', 'combinação ausente ou duas tarifas vigentes não recebe valor inventado')

    'LOC-01' = @('corporation_sequence_number válido é candidato rastreado e pesos textuais convertem estritamente', 'sequence_number de ordenação ou número inválido não prova identidade nem vira zero')
    'LOC-02' = @('mudança de status/região/previsão altera hash e preserva responsável e soft delete', 'campo ausente em resposta parcial não apaga estado conhecido')
    'LOC-03' = @('invoices_volumes nulo usa volume de Fretes; ambos nulos publicam zero', 'volume local igual a zero não é substituído pelo fallback de Fretes')
    'LOC-04' = @('texto numérico válido converte para tipo/escala aprovados', 'texto inválido é quarentenado e não vira nulo silencioso')
    'LOC-05' = @('timestamp com precedência caracterizada impede regressão out-of-order', 'dois nulos ou empate sem desempate provado vão à quarentena, não keep-last')
    'LOC-06' = @('status branco publica sem_status; " Delivering " normaliza para delivering preservando bruto', 'status desconhecido não herda terminalidade nem cancelamento')
    'LOC-07' = @('status_branch_nickname permanece ABSENT/UNSOURCED até surgir source path comprovado', 'nickname parecido não é usado como fallback inventado')

    'CAP-01' = @('contador e travessia usam a mesma janela issue_date e o mesmo dia created_at', 'contador que omite created_at não é oráculo do conjunto percorrido')
    'CAP-02' = @('paid=true publica PAGO e paid=false publica ABERTO', 'nulo ou texto truthy não é convertido silenciosamente em PAGO')
    'CAP-03' = @('maior instante entre transação, liquidação e criação é usado em dedupe e promoção', 'comparação lexicográfica ou expressão divergente entre dedupe/promoção é rejeitada')
    'CAP-04' = @('parcela preserva ant_ils_sequence_code e segue em sombra sem prova da raiz/completude', 'per ou duas travessias iguais não habilitam sweep/cutover')
    'CAP-05' = @('Accounting::Advance publica Adiantamento e variable_costs publica Custos Variáveis', 'valor desconhecido preserva bruto e não assume catálogo conhecido')

    'FAT-01' = @('id=FAT-A permanece source key candidata escopada; título lógico usa crosswalk próprio', 'unique_id ausente no payload ou order_by não prova source key')
    'FAT-02' = @('CT-e e NFS-e simultâneos ficam ambos no staging com proveniência e bloqueiam saída até ADR', 'mapper não pode zerar uma evidência nem core/view usar precedências divergentes')
    'FAT-03' = @('uma fatura relaciona dois fretes por crosswalk sem duplicar a raiz', 'fit_ant_document não é convertido em identidade de Frete')
    'FAT-04' = @('rekey mantém alias histórico e replay reproduz as mesmas relações/cardinalidades', 'mudança de chave não reescreve vínculo silenciosamente nem cria N:N acidental')
    'FAT-05' = @('data civil usa início do dia seguinte em America/Sao_Paulo; CT-e conserva hora', '23:59:59 literal, timezone do host ou keep-last não define frescor')
    'FAT-06' = @('authorized publica Autorizado e Freight::Express publica Express preservando bruto', 'status desconhecido não recebe label conhecida nem perde o original')
    'FAT-07' = @('serie_nfse permanece ABSENT/UNSOURCED e bloqueada até evidência ou retirada aceita', 'campo não é declarado obrigatório nem preenchido por número parecido')

    'INV-01' = @('sequence_code cria raiz candidata e fretes/invoices ficam em filhos naturais', 'hash composto legado não é copiado como identidade única da raiz')
    'INV-02' = @('performance_finished_at vence finished_at e started_at', 'chegada posterior não supera um timestamp de maior precedência')
    'INV-03' = @('evidência normalizada de comprovante mantém flag verdadeira por OR cumulativo', 'snapshot sem palavra-chave não faz true regredir para false')
    'INV-04' = @('minuta válida e texto reconhecido produzem relação/derivado com proveniência', 'minuta ambígua ou parsing inválido vai à quarentena sem join inventado')

    'SIN-01' = @('sequence_code obrigatório cria raiz candidata e ocorrências/fretes mantêm componentes', 'sequence_code nulo ou hash composto sem prova não cria identidade canônica')
    'SIN-02' = @('treatment_at presente vence opening_at_date em dedupe e promoção', 'dedupe só por treatment_at não pode escolher linha diferente da promoção')

    'USR-01' = @('mesmo user_id e hash igual atualiza auditoria sem nova versão; hash diferente cria histórico', 'nome igual com user_id diferente não colapsa usuários')
    'USR-02' = @('duas travessias completas autorizadas podem desativar; reaparecimento reativa', 'uma página parcial ou usuário de evento de Coleta não desativa/multiplica dimensão')
    'USR-03' = @('GraphQL id/name permanece fonte transitória sem alegar incremental temporal', 'troca por Data Export sem template/contrato/paridade é recusada')
    'USR-04' = @('9901 permanece apenas identidade de auditoria e updatedAt fica UNREQUESTED', 'não chamar reports/9901 nem inventar updatedAt por existir no DTO')

    'RAS-01' = @('pai cod_solicitacao é promovido com filhos ordenados na mesma transação', 'filho órfão ou falha parcial não confirma pai sem filhos')
    'RAS-02' = @('timezone IANA e regra de frescor/snapshot versionadas impedem regressão', 'ZoneId do host e overwrite cego não definem contrato')
    'RAS-03' = @('lote abaixo do cap e terminalidade provada conclui a menor janela permitida', '500 itens ou cap persistente não é tratado como fim da travessia')
    'RAS-04' = @('módulo desligado retorna NOT_APPLICABLE; habilitado sem credencial falha no startup', 'falha de pai/filhos não vira sucesso ou degradação silenciosa')
    'RAS-05' = @('sentinela 1900-01-01 vira nulo com bruto; duração 60 minutos permanece válida', 'duração negativa/acima de 43200 ou formato do host gera métrica e inválido')
    'RAS-06' = @('Ordem fornecida participa da chave do filho após prova de estabilidade', 'posição i+1 usada quando Ordem falta permanece UNRESOLVED e não vira identidade')

    'MAT-01' = @('PE com previsão/finalização iguais publica NO PRAZO/1 e preserva fallbacks', 'entrada inelegível, cancelada ou com grão conflitante não gera/duplica indicador')
    'MAT-02' = @('dia+filial+Geral agrega Manifestos/Inventário distintos e denominador zero publica 0%', 'primeira filial lexicográfica após split não é aceita sem ADR')
    'MAT-03' = @('dia útil, CT-e priorizado e regra pagador→filial vigente produzem uma linha no grão aprovado', 'soft-delete/cancelamento/bloqueio ou conflito frete×data mantém receita zero/bloqueia grão')
    'MAT-04' = @('documento não-placeholder, cliente normalizado e aging por relógio injetado geram estado determinístico', 'placeholder faturado ou conflito unique_id×emissão não decide grão/status sem ADR')
    'MAT-05' = @('uma raiz por sequence_code soma cada Frete/Coleta uma vez e exclui ACM0000', 'expansão pick/MDF-e não pode sintetizar MAX nem duplicar SUM')

    'PUB-01' = @('Frete ativo não complementar publica CT-e antes de NFS-e e status done=finalizado', 'Frete excluído/complementar ou evidência duplicada não é publicado/multiplicado')
    'PUB-02' = @('primeira ausência publica Excluída e região resolve CEP antes de cidade/UF sem multiplicar', 'join com vários manifestos/usuários não duplica Coleta nem muda status bruto')
    'PUB-03' = @('documento emitido publica Convertida; sem documento com reprovação publica Reprovada', 'combinação tarifária ausente não recebe tarifa default')
    'PUB-04' = @('Conta PAGO publica Sim; Fatura ativa prioriza CT-e e CNPJ explícito', 'placeholder/documento divergente entre fato/view mantém contrato bloqueado')
    'PUB-05' = @('delivered publica Entregue terminal e alias ausente publica SEM_MAP', 'status desconhecido não vira terminal/cancelado por semelhança')
    'PUB-06' = @('Inventário Loading publica Carregamento e Sinistro conhecido recebe label versionada', 'tipo/status desconhecido preserva bruto em vez de receber tradução próxima')
    'PUB-07' = @('dimensão Veículo deduplica placa+filial e monitoramento permanece em ctl', 'nome parecido não colapsa grão dimensional nem expõe monitoramento em pub')
    'PUB-08' = @('Raster mantido usa transit time direto=60 e extração mais recente entre pai/filho', 'módulo não aprovado, duração fora de 0..43200 ou parsing incerto não publica a view')
}
