package br.com.esl.etl.v2.plataforma.reconciliacao.sweep;

/** Precedência fechada, na ordem em que o kernel a avalia. */
public enum SweepPreviewBlockReason {
    MODE_NOT_SWEEP,
    APPLICABILITY_NOT_ENABLED,
    RESPONSIBILITY_KIND_NOT_ELIGIBLE,
    SOURCE_COMPLETENESS_NOT_PROVEN,
    EVIDENCE_STATUS_NOT_PROVEN,
    TRAVERSAL_INCOMPLETE,
    MISSING_PAGE,
    CAP_REACHED,
    TIMEOUT_OR_CANCELLATION,
    ANOMALOUS_EMPTY_SOURCE,
    INVALID_LIMIT_EXCEEDED,
    QUARANTINE_LIMIT_EXCEEDED,
    VOLUME_LIMIT_EXCEEDED,
    HISTORY_LIMIT_EXCEEDED,
    HIERARCHY_UNSAFE,
    NOMINAL_OWNER_MISSING,
    EVIDENCE_POLICY_MISMATCH,
    EVIDENCE_SCOPE_MISMATCH,
    SNAPSHOT_FINGERPRINT_MISMATCH,
    BINDING_FINGERPRINT_MISMATCH,
    TRAVERSAL_EVIDENCE_NOT_INDEPENDENT,
    ABSENCE_EVIDENCE_NOT_INDEPENDENT,
    CROSS_EVIDENCE_NOT_INDEPENDENT,
    NONE_PREVIEW_ELIGIBLE_NO_APPLY_CAPABILITY
}
