-- Baseline estrutural V2 gerado a partir do manifesto de fundação.
-- Execute somente em banco V2 vazio já aprovado. Não execute este arquivo pelo Flyway:
-- o Flyway usa as migrations versionadas em ../migrations e mantém seu próprio histórico.

:r "..\migrations\V001__create_v2_schema_foundation.sql"
:r "..\migrations\V002__create_v2_database_roles.sql"
:r "..\migrations\V003__create_control_plane.sql"
:r "..\migrations\V004__create_staging_promotion_kernel.sql"
:r "..\migrations\V005__create_staging_lifecycle.sql"
:r "..\migrations\V006__create_observability_data_quality.sql"
:r "..\migrations\V007__create_usuarios_current_history.sql"
:r "..\migrations\V008__create_governed_references.sql"
:r "..\migrations\V009__create_usuario_dimension_current_view.sql"
:r "..\migrations\V010__create_coletas_shadow_vertical.sql"
:r "..\migrations\V011__create_cotacoes_shadow_vertical.sql"
:r "..\migrations\V012__create_manifestos_shadow_vertical.sql"
:r "..\migrations\V013__create_fretes_shadow_vertical.sql"
:r "..\migrations\V014__create_localizacao_cargas_shadow_vertical.sql"
:r "..\migrations\V015__create_runtime_durable_recovery.sql"
:r "..\migrations\V016__create_windows_runtime_authority.sql"
:r "..\migrations\V017__create_runtime_temporal_plan.sql"
:r "..\migrations\V018__enforce_durable_runtime_consumers.sql"
:r "..\migrations\V019__create_scoped_runtime_observability.sql"
:r "..\migrations\V020__bind_existing_runtime_occurrences.sql"
:r "..\migrations\V021__bind_durable_temporal_intent.sql"
:r "..\migrations\V022__extend_five_vertical_runtime.sql"
:r "..\migrations\V023__correct_scoped_runtime_output_projection.sql"
